*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jul 23 23:14:12 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: 6536c6bcec47
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x56011b798600
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
ModuleNotFoundError: No module named 'quick_django.wsgi'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 598)
spawned uWSGI worker 1 (pid: 602, cores: 1)
Python auto-reloader enabled
--- no python application found, check your startup logs for errors ---
[pid: 602|app: -1|req: -1/1] 192.168.128.1 () {56 vars in 1111 bytes} [Fri Jul 23 23:14:16 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 602|app: -1|req: -1/2] 192.168.128.1 () {56 vars in 1065 bytes} [Fri Jul 23 23:14:16 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 602|app: -1|req: -1/3] 192.168.128.1 () {56 vars in 1111 bytes} [Fri Jul 23 23:14:19 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 602|app: -1|req: -1/4] 192.168.128.1 () {56 vars in 1065 bytes} [Fri Jul 23 23:14:19 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 602|app: -1|req: -1/5] 192.168.128.1 () {56 vars in 1111 bytes} [Fri Jul 23 23:14:20 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 602|app: -1|req: -1/6] 192.168.128.1 () {56 vars in 1065 bytes} [Fri Jul 23 23:14:20 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Fri Jul 23 23:14:47 2021 - *** PAUSE (press start to resume, if you do not have a joypad send SIGTSTP) ***
Fri Jul 23 23:14:47 2021 - *** worker 1 suspended ***
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jul 23 23:15:41 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: 07a8e295e192
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x563a4e348600
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
ModuleNotFoundError: No module named 'quick_django.wsgi'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 385)
spawned uWSGI worker 1 (pid: 386, cores: 1)
Python auto-reloader enabled
--- no python application found, check your startup logs for errors ---
[pid: 386|app: -1|req: -1/1] 192.168.128.1 () {56 vars in 1111 bytes} [Fri Jul 23 23:15:43 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 386|app: -1|req: -1/2] 192.168.128.1 () {56 vars in 1065 bytes} [Fri Jul 23 23:15:43 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Fri Jul 23 23:15:47 2021 - *** PAUSE (press start to resume, if you do not have a joypad send SIGTSTP) ***
Fri Jul 23 23:15:47 2021 - *** worker 1 suspended ***
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jul 23 23:34:10 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: 65313972d11b
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x55a25f9da600
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
ModuleNotFoundError: No module named 'quick_django.wsgi'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 720)
spawned uWSGI worker 1 (pid: 721, cores: 1)
Python auto-reloader enabled
invalid request block size: 21573 (max 4096)...skip
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jul 23 23:37:09 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: 65313972d11b
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8081).
bind(): Address already in use [core/socket.c line 769]
invalid request block size: 21573 (max 4096)...skip
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:09:57 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: 05abba1ca882
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app/quick_django
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x560091d111b0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x560091d111b0 pid: 7 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 9, cores: 1)
Python auto-reloader enabled
invalid request block size: 21573 (max 4096)...skip
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:11:38 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: 3aaaaaed8a69
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app/quick_django
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x557e160501b0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x557e160501b0 pid: 8 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8)
spawned uWSGI worker 1 (pid: 34, cores: 1)
Python auto-reloader enabled
invalid request block size: 21573 (max 4096)...skip
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:12:43 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: 3aaaaaed8a69
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app/quick_django
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8081).
bind(): Address already in use [core/socket.c line 769]
invalid request block size: 21573 (max 4096)...skip
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:14:17 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: d4202985e0ce
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app/quick_django
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x5638f1058640
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5638f1058640 pid: 323 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 323)
spawned uWSGI worker 1 (pid: 325, cores: 1)
Python auto-reloader enabled
invalid request block size: 21573 (max 4096)...skip
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 0 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:15:16 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: d4202985e0ce
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app/quick_django
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8081 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43331 (port auto-assigned) fd 3
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x560f00536c60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x560f00536c60 pid: 530 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 530)
spawned uWSGI worker 1 (pid: 532, cores: 1)
spawned uWSGI http 1 (pid: 533)
Python auto-reloader enabled
[pid: 532|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 294 bytes} [Sat Jul 24 00:15:21 2021] GET / => generated 16493 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 533)
worker 1 buried after 0 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:15:29 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: d4202985e0ce
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app/quick_django
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x559a82739640
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x559a82739640 pid: 594 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 594)
spawned uWSGI worker 1 (pid: 596, cores: 1)
Python auto-reloader enabled
[pid: 596|app: 0|req: 1/1] 192.168.176.1 () {54 vars in 1080 bytes} [Sat Jul 24 00:15:34 2021] GET / => generated 16493 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
Not Found: /static/admin/css/fonts.css
[pid: 596|app: 0|req: 2/2] 192.168.176.1 () {52 vars in 996 bytes} [Sat Jul 24 00:15:34 2021] GET /static/admin/css/fonts.css => generated 2023 bytes in 7 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 596|app: 0|req: 3/3] 192.168.176.1 () {52 vars in 1012 bytes} [Sat Jul 24 00:15:34 2021] GET /favicon.ico => generated 1978 bytes in 4 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
invalid request block size: 21573 (max 4096)...skip
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:18:52 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: 5a713f4ba8dd
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/python/app/quick_django
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x55da837a31f0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55da837a31f0 pid: 7 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 19, cores: 1)
Python auto-reloader enabled
invalid request block size: 21573 (max 4096)...skip
[pid: 19|app: 0|req: 1/1] 192.168.176.1 () {56 vars in 1111 bytes} [Sat Jul 24 00:19:05 2021] GET / => generated 16493 bytes in 10 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
Not Found: /static/admin/css/fonts.css
[pid: 19|app: 0|req: 2/2] 192.168.176.1 () {52 vars in 996 bytes} [Sat Jul 24 00:19:05 2021] GET /static/admin/css/fonts.css => generated 2023 bytes in 5 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
[pid: 19|app: 0|req: 3/3] 192.168.176.1 () {56 vars in 1111 bytes} [Sat Jul 24 00:19:06 2021] GET / => generated 16493 bytes in 4 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
Not Found: /static/admin/css/fonts.css
[pid: 19|app: 0|req: 4/4] 192.168.176.1 () {52 vars in 996 bytes} [Sat Jul 24 00:19:06 2021] GET /static/admin/css/fonts.css => generated 2023 bytes in 4 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
[pid: 19|app: 0|req: 5/5] 192.168.176.1 () {56 vars in 1111 bytes} [Sat Jul 24 00:19:06 2021] GET / => generated 16493 bytes in 6 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
Not Found: /static/admin/css/fonts.css
[pid: 19|app: 0|req: 6/6] 192.168.176.1 () {52 vars in 996 bytes} [Sat Jul 24 00:19:06 2021] GET /static/admin/css/fonts.css => generated 2023 bytes in 4 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
[pid: 19|app: 0|req: 7/7] 192.168.176.1 () {56 vars in 1111 bytes} [Sat Jul 24 00:19:06 2021] GET / => generated 16493 bytes in 3 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
Not Found: /static/admin/css/fonts.css
[pid: 19|app: 0|req: 8/8] 192.168.176.1 () {52 vars in 996 bytes} [Sat Jul 24 00:19:06 2021] GET /static/admin/css/fonts.css => generated 2023 bytes in 6 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:37:34 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: c549db218625
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/python/app/quick_django
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x5637f99061f0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5637f99061f0 pid: 7 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 33, cores: 1)
Python auto-reloader enabled
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:43:48 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: c549db218625
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/python/app/quick_django
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x5650a66a71f0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5650a66a71f0 pid: 8 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8)
spawned uWSGI worker 1 (pid: 10, cores: 1)
Python auto-reloader enabled
Internal Server Error: /main/temp
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./main/views.py", line 13, in temp
    return render(request, 'main/temp.html', context)
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: main/temp.html
[pid: 10|app: 0|req: 1/1] 192.168.176.1 () {54 vars in 1098 bytes} [Sat Jul 24 00:45:34 2021] GET /main/temp => generated 73558 bytes in 88 msecs (HTTP/1.1 500) 5 headers in 156 bytes (1 switches on core 0)
Internal Server Error: /main/temp
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./main/views.py", line 13, in temp
    return render(request, 'main/temp.html', context)
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: main/temp.html
[pid: 10|app: 0|req: 2/2] 192.168.176.1 () {56 vars in 1129 bytes} [Sat Jul 24 00:46:23 2021] GET /main/temp => generated 73695 bytes in 39 msecs (HTTP/1.1 500) 5 headers in 156 bytes (1 switches on core 0)
Internal Server Error: /main/temp
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./main/views.py", line 13, in temp
    return render(request, 'main/temp.html', context)
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: main/temp.html
[pid: 10|app: 0|req: 3/3] 192.168.176.1 () {56 vars in 1129 bytes} [Sat Jul 24 00:46:25 2021] GET /main/temp => generated 73695 bytes in 56 msecs (HTTP/1.1 500) 5 headers in 156 bytes (1 switches on core 0)
[uwsgi-python-reloader] module/file ./main/views.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 10)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:8081)
running /usr/local/bin/uwsgi
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jul 24 00:47:13 2021] ***
compiled with version: 8.3.0 on 23 July 2021 14:12:06
os: Linux-4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
nodename: c549db218625
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/python/app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/python/app/quick_django
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :8081 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
Python main interpreter initialized at 0x55ff0a169190
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55ff0a169190 pid: 8 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 8)
spawned uWSGI worker 1 (pid: 1027, cores: 1)
Python auto-reloader enabled
[pid: 1027|app: 0|req: 1/1] 192.168.176.1 () {56 vars in 1129 bytes} [Sat Jul 24 00:47:18 2021] GET /main/temp => generated 297 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 1027|app: 0|req: 2/2] 192.168.176.1 () {56 vars in 1129 bytes} [Sat Jul 24 00:47:20 2021] GET /main/temp => generated 297 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
